[FROMLIST-EXYNOS7870] [include] linux: patch pagemap.h
original base: A600FNXXU9CVB1 rebase: lineage-18.1-exynos7870-3.18-android-mainline-2.0

history: 53b9f15d189 [FROMLIST-EXYNOS7870] [include] linux: patch pagemap.h
047ee99d3cb Merge remote-tracking branch 'origin/upstream-f2fs-stable-linux-3.18.y' into android-3.18
e413f9de9e5 mm: implement find_get_pages_range_tag()
bbb325e7eba mm: Fix false-positive VM_BUG_ON() in page_cache_{get,add}_speculative()
400f32af8fa fix fault_in_multipages_...() on architectures with no-op access_ok()
513c6682033 mm: get rid of radix tree gfp mask for pagecache_get_page
9d1ba805647 mm/balloon_compaction: remove balloon mapping and flag AS_BALLOON_MAP
25641c0c8d7 Merge tag 'nfs-for-3.18-1' of git://git.linux-nfs.org/projects/trondmy/linux-nfs
28596c97222 Merge branch 'for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/jikos/trivial
a4796e37c12 MM: export page_wakeup functions
cbbce822094 SCHED: add some "wait..on_bit...timeout()" interfaces.
50d8a189013 linux/pagemap.h: Fixed a typo in a code comment.
9a95f3cf7b3 mm: describe mmap_sem rules for __lock_page_or_retry() and callers
a0f7a756c2f mm/rmap.c: fix pgoff calculation to handle hugepage correctly
2457aec6374 mm: non-atomically mark page accessed during page cache allocation where possible
b745bc85f21 mm: page_alloc: convert hot/cold parameter and immediate callers to bool
57d998456ae fs/mpage.c: factor page_endio() out of mpage_end_io()
67f9fd91f93 mm: remove read_cache_page_async()
91b0abe36a7 mm + fs: store shadow entries in page cache
0cd6144aadd mm + fs: prepare for non-page entries in page cache radix trees
e7b563bb2a6 mm: filemap: move radix tree hole searching here
309381feaee mm: dump page when hitting a VM_BUG_ON using VM_BUG_ON_PAGE
8375ad98cc1 vm: adjust ifdef for TINY_RCU
1d1d1a76720 mm: only enforce stable page writes if the backing device requires it
18468d93e53 mm: introduce a common interface for balloon pages mobility
f981c5950fa mm: methods for teaching filesystems about PG_swapcache pages
af2e840971d pagemap.h: fix warning about possibly used before init var
9923777dff4 mm: fixup compilation error due to an asm write through a const pointer
f56f821feb7 mm: extend prefault helpers to fault in more than PAGE_SIZE
5e5358e7cf4 mm: cleanup descriptions of filler arg
bdd4e85dc36 sched: Isolate preempt counting in its own config option
7b1de5868b1 readahead: readahead page allocations are OK to fail
f62e00cc3a0 mm: introduce wait_on_page_locked_killable()
6c510389005 Merge branch 'for-2.6.39/core' of git://git.kernel.dk/linux-2.6-block
e64a782fec6 mm: change __remove_from_page_cache()
702cfbf93aa mm: goodbye remove_from_page_cache()
97cecb5a254 mm: introduce delete_from_page_cache()
ef6a3c63112 mm: add replace_page_cache_page() function
7eaceaccab5 block: remove per-queue plugging
088e54658f5 mm: remove likely() from mapping_unevictable()
d065bd810b6 mm: retry page fault when blocking on disk transfer
1021a645344 Merge branch 'hwpoison' of git://git.kernel.org/pub/scm/linux/kernel/git/ak/linux-mce-2.6
0fe6e20b9c4 hugetlb, rmap: add reverse mapping for hugepage
8edf344c66a hugetlb: move definition of is_vm_hugetlb_page() to hugepage_inline.h
627295e4926 gcc-4.6: pagemap: avoid unused-but-set variable
0531b2aac59 mm: add new 'read_cache_page_gfp()' helper function
b560d8ad858 rcu: Expunge lingering references to CONFIG_CLASSIC_RCU, optimize on !SMP
6837765963f mm: remove CONFIG_UNEVICTABLE_LRU config option
385e1ca5f21 CacheFiles: Permit the page lock state to be monitored
9a896c9a48a mm: define a UNIQUE value for AS_UNEVICTABLE flag
54566b2c159 fs: symlink write_begin allocation context fix
8413ac9d8c9 mm: page lock use lock bitops
f45840b5c12 mm: pagecache insertion fewer atomics
89e004ea55a SHM_LOCKED pages are unevictable
ba9ddf49391 Ramfs and Ram Disk pages are unevictable
529ae9aaa08 mm: rename page trylock
ce0ad7f0952 powerpc/mm: Lockless get_user_pages_fast() for 64-bit (v3)
7906d00cd1f mmu-notifiers: add mm_take_all_locks() operation
e286781d5f2 mm: speculative page references
2185e69f680 mapping_set_error: add unlikely()
b3c97528689 include/linux: Remove all users of FASTCALL() macro
2687a3569e4 Add lock_page_killable
afddba49d18 fs: introduce write_begin, write_end, and perform_write aops
08291429cfa mm: fix pagecache write deadlocks
57f6b96c09c filemap: convert some unsigned long to pgoff_t
3e9f45bd181 Factor outstanding I/O error handling
6fe6900e1e5 mm: make read_cache_page synchronous
62045305c20 [PATCH] mm: remove find_trylock_page
2ae88149a27 [PATCH] mm: clean up pagecache allocation
db37648cd6c [PATCH] mm: non syncing lock_page()
347ce434d57 [PATCH] zoned vm counters: conversion of nr_pagecache to per zone counter
090d2b185d8 [PATCH] read_mapping_page for address space
ebf43500ef1 [PATCH] Add find_get_pages_contig(): contiguous variant of find_get_pages()
93fac7041f0 [PATCH] mm: schedule find_trylock_page() removal
44110fe385a [PATCH] cpuset memory spread page cache implementation and hooks
2d6c666e870 [PATCH] mm: gfp_noreclaim cleanup
260b23674fd [PATCH] gfp_t: the rest
6daa0e28627 [PATCH] gfp_t: mm/* (easy parts)
dd0fc66fb33 [PATCH] gfp flags annotations - part 1
0c35bbadc59 [PATCH] VM: add __GFP_NORECLAIM
1da177e4c3f Linux-2.6.12-rc2