[FROMLIST-EXYNOS7870] [mm] mm: patch Kconfig
original base: A600FNXXU9CVB1 rebase: lineage-18.1-exynos7870-3.18-android-mainline-2.0

history: 20e6ce065db [FROMLIST-EXYNOS7870] [mm] mm: patch Kconfig
37ab96626d1 UPSTREAM: mm/zsmalloc: add statistics support
09316c09dde mm/balloon_compaction: add vmstat counters and kpageflags bit
2667f50e8b8 mm: introduce a general RCU get_user_pages_fast()
12d79d64bfd mm/zpool: update zswap to use zpool
af8d417a045 mm/zpool: implement common zpool api to zbud/zsmalloc
a254129e868 CMA: generalize CMA reserved area management functionality
d867f203b97 mm/zsmalloc: make zsmalloc module-buildable
226b4ccdcb6 mm/process_vm_access: move config option into init/Kconfig
c177c81e09e hugetlb: restrict hugepage_migration_support() to x86_64
70210ed950b mm/memblock: add physical memory list
042d27acb64 parisc,metag: Do not hardcode maximum userspace stack size
9e5c33d7aee mm: create generic early_ioremap() support
9164550ecd1 mm: disable split page table lock for !MMU
2216ee85301 mm/Kconfig: fix URL for zsmalloc benchmark
bcf1647d089 zsmalloc: move it under mm
a844f38671d mm: add missing dependency in Kconfig
9073e1a804c Merge branch 'for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/jikos/trivial
49076ec2cca mm: dynamically allocate page->ptl if it cannot be embedded to struct page
e009bb30c8d mm: implement split page table lock for PMD level
e9bb18c7b95 mm: avoid increase sizeof(struct page) due to split page table lock
c5320926e37 mem-hotplug: introduce movable_node boot option
18f6533277c mm/Kconfig: Grammar s/an/a/
f7e3334a6bc powerpc: Fix memory hotplug with sparse vmemmap
de32a8177f6 mm/Kconfig: add MMU dependency for MIGRATION.
bf550fc93d9 Merge remote-tracking branch 'origin/next' into kvm-ppc-next
2b2811178e8 zswap: add to mm/
4e2e2770b15 zbud: add to mm/
20f7462aac0 Merge remote-tracking branch 'cmadma/for-v3.12-cma-dma' into kvm-ppc-next
0f8975ec4db mm: soft-dirty bits for user memory changes tracking
f825c736e75 mm/cma: Move dma contiguous changes into a seperate config
40b313608ad Finally eradicate CONFIG_HOTPLUG
9ca24e2e193 mmKconfig: add an option to disable bounce
4febd95a8a8 Select VIRT_TO_BUS directly where needed
887cbce0ade arch Kconfig: centralise CONFIG_ARCH_NO_VIRT_TO_BUS
46723bfa540 memory-hotplug: implement register_page_bootmem_info_section of sparse-vmemmap
7c2db36e730 Merge branch 'akpm' (incoming from Andrew)
ffecfd1a72f block: optionally snapshot page contents to provide stable pages during write
a8826eeb71b mm: remove depends on CONFIG_EXPERIMENTAL
c2974058a9c memory-hotplug: document and enable CONFIG_MOVABLE_NODE
f6e858a00af Merge branch 'akpm' (Andrew's patch-bomb)
20b2f52b73f numa: add CONFIG_MOVABLE_NODE for movable-dedicated node
18468d93e53 mm: introduce a common interface for balloon pages mobility
05106e6a54a mm: enable CONFIG_COMPACTION by default
15626062f4a thp, x86: introduce HAVE_ARCH_TRANSPARENT_HUGEPAGE
ee6f509c327 mm: factor out memory isolate functions
a3fe778c789 Merge tag 'stable/frontswap.v16-tag' of git://git.kernel.org/pub/scm/linux/kernel/git/konrad/mm
5febcbe99d4 Cross Memory Attach: make it Kconfigurable
47118af076f mm: mmzone: MIGRATE_CMA migration type added
27c6aec2142 mm: frontswap: config and doc files
d4bbf7e7759 Merge branch 'master' into x86/memblock
6661672053a memblock: add NO_BOOTMEM config symbol
c378ddd53f9 memblock, x86: Make ARCH_DISCARD_MEMBLOCK a config option
7c0caeb866b memblock: Add optional region->nid
140a1ef2f91 mm Kconfig typo: cleancacne -> cleancache
077b1f83a69 mm: cleancache core ops functions and config
33a938774fd mm: compaction: don't depend on HUGETLB_PAGE
5d6892407ca thp: select CONFIG_COMPACTION if TRANSPARENT_HUGEPAGE enabled
13ece886d99 thp: transparent hugepage config choice
f2d6bfe9ff0 thp: add x86 32bit support
4c76d9d1fb9 thp: CONFIG_TRANSPARENT_HUGEPAGE
0fc0531e0a2 Merge branch 'for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/tj/percpu
152e0659fc0 mm: avoid warning when COMPACTION is selected
bbddff05458 percpu: use percpu allocator on UP too
95f72d1ed41 lmb: rename to memblock
e9e96b39f93 mm: allow CONFIG_MIGRATION to be set without CONFIG_NUMA or memory hot-remove
a626b46e17d Merge branch 'x86-bootmem-for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/linux-2.6-tip
9bdac914240 sparsemem: Put mem map for one node together.
0176bd3dab4 sh: Drop down to a single quicklist.
27df5068e24 HWPOISON: Add PROC_FS dependency to hwpoison injector v2
6e141546761 NOMMU: Optimise away the {dac_,}mmap_min_addr tests
413f9efbc51 HWPOISON: mention HWPoison in Kconfig entry
478c5ffc0b5 HWPOISON: add page flags filter
d0f209f68f8 ksm: remove unswappable max_kernel_pages
a70caa8ba48 mm: stop ptlock enlarging struct page
af8e3354b4b mm: CONFIG_MMU for PG_mlocked
6ad696d2cf5 mm: allow memory hotplug and hibernation in the same kernel
0a53f1693cb Merge branch 'merge' of git://git.kernel.org/pub/scm/linux/kernel/git/benh/powerpc
1a83e175dc2 mm: fix sparsemem configuration
ed84a07a124 powerpc: Limit memory hotplug support to PPC64 Book-3S machines
c73602ad31c ksm: more on default values
d949f36f186 x86: Fix hwpoison code related build failure on 32-bit NUMAQ
db16826367f Merge branch 'hwpoison' of git://git.kernel.org/pub/scm/linux/kernel/git/ak/linux-mce-2.6
7701c9c0f54 ksm: add some documentation
f8af4da3b4c ksm: the mm interface to ksm
cae681fc12a HWPOISON: Add simple debugfs interface to inject hwpoison on arbitary PFNs
6a46079cf57 HWPOISON: The high level memory error handler in the VM v7
227423904c7 Merge branch 'x86-pat-for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/linux-2.6-tip
a269cca9926 mm: remove !NUMA condition from PAGEFLAGS_EXTENDED condition set
788084aba2a Security/SELinux: seperate lsm specific mmap_min_addr
517d08699b2 Merge branch 'akpm'
6837765963f mm: remove CONFIG_UNEVICTABLE_LRU config option
03997904983 [S390] pm: memory hotplug power management callbacks
e0a94c2a63f security: use mmap_min_addr indepedently of security models
fc4d5c292b6 nommu: make the initial mmap allocation excess behaviour Kconfig configurable
5a52edded38 mm: point the UNEVICTABLE_LRU config option at the documentation
71aa653c6bf nommu: make CONFIG_UNEVICTABLE_LRU available when CONFIG_MMU=n
33925b25d2c nommu: there is no mlock() for NOMMU, so don't provide the bits
67faaada1eb Remove obsolete CONFIG_RESOURCES_64BIT
894bc310419 Unevictable LRU Infrastructure
e533b227055 Merge branch 'core-v28-for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/tip/linux-2.6-tip
9ba16087d9f Kconfig: eliminate "def_bool n" constructs
600715dcdf5 generic: add phys_addr_t for holding physical addresses
912985dce45 mm: Make generic weak get_user_pages_fast and EXPORT_GPL it
cddb8a5c14a mmu-notifiers: core
8174c430e44 x86: lockless get_user_pages_fast()
83d1674a946 mm: make CONFIG_MIGRATION available w/o CONFIG_NUMA
6c118e43dc5 Merge git://git.kernel.org/pub/scm/linux/kernel/git/hskinnemoen/avr32-2.6
421c175c4d6 [S390] Add support for memory hot-add.
38510754a50 avr32: Use a quicklist for PTE allocation as well
e20b8cca760 PAGEFLAGS_EXTENDED and separate page flags for Head and Tail
d5f68c6dbda sh: Bump number of quicklists for SH-5.
a5ee6daa525 sparsemem: make SPARSEMEM_VMEMMAP selectable
ad3d0a3827a small documentation fixes
fb9fc395174 Merge branch 'xen-upstream' of git://git.kernel.org/pub/scm/linux/kernel/git/jeremy/xen
74260714c56 xen: lock pte pages while pinning/unpinning
0c0e6195896 memory unplug: page offline
29c71111d05 vmemmap: generify initialisation via helpers
67dd5a25f4e xen: disable split pte locks for now
b0cb1a19d05 Replace CONFIG_SOFTWARE_SUSPEND with CONFIG_HIBERNATION
2a7326b5bba CONFIG_BOUNCE to avoid useless inclusion of bounce buffer logic
b91cba52e9b Merge master.kernel.org:/pub/scm/linux/kernel/git/lethal/sh-2.6
f057eac0d7a Introduce CONFIG_VIRT_TO_BUS
33d63bd83bf sh: memory hot-add for sparsemem users support.
6c645ac7258 sh64: generic quicklist support.
5f8c9908f20 sh: generic quicklist support.
6225e93735a Quicklists for page table pages
5ac6da669e2 [PATCH] Set CONFIG_ZONE_DMA for arches with GENERIC_ISA_DMA
4b51d669892 [PATCH] optional ZONE_DMA: optional ZONE_DMA in the VM
66701b1499a [PATCH] optional ZONE_DMA: introduce CONFIG_ZONE_DMA
84eb8d0608a Fix "can not" in Documentation and Kconfig
44c09201a41 more misc typo fixes
ec69acbb119 [PATCH] hot-add-mem x86_64: Kconfig changes
1903ac54f85 Merge master.kernel.org:/pub/scm/linux/kernel/git/gregkh/pci-2.6
cc57637b0b0 [PATCH] solve config broken: undefined reference to `online_page'
1f04bbd2d39 [PATCH] sparc64: support sparsemem and !memory hotplug
6550e07f41c [PATCH] 64bit Resource: finally enable 64bit resource sizes
6c5240ae7f4 [PATCH] Swapless page migration: modify core logic
d784124cfe9 [PATCH] mm: make page migration dependent on swap and NUMA
b20a35035f9 [PATCH] page migration reorg
7cbe34cf86c [PATCH] Swap Migration V5: Add CONFIG_MIGRATION for page migration support
c898ec16e83 [PATCH] allow flatmem to be disabled when only sparsemem is implemented
7b6ac9dffe6 [PATCH] mm: update split ptlock Kconfig
2d4b95f0606 [PATCH] Suppress split ptlock on arches which may use one page for multiple page tables
3947be1969a [PATCH] memory hotplug: sysfs and add/remove functions
4c21e2f2441 [PATCH] mm: split page table lock
f3519f91942 [PATCH] fix mm/Kconfig spelling
3e347261a80 [PATCH] sparsemem extreme implementation
802f192e4a6 [PATCH] SPARSEMEM EXTREME
d41dee369bf [PATCH] sparsemem memory model
af705362ab6 [PATCH] generify memory present
785dcd44b60 [PATCH] mm/Kconfig: give DISCONTIG more help text
e1785e85b9c [PATCH] mm/Kconfig: hide "Memory Model" selection menu
44d0f805c77 [PATCH] sparsemem: fix minor "defaults" issue in mm/Kconfig
93b7504e3e6 [PATCH] Introduce new Kconfig option for NUMA or DISCONTIG
3a9da7655d2 [PATCH] create mm/Kconfig for arch-independent memory options