[FROMLIST-EXYNOS7870] [mm] mm: patch migrate.c
original base: A600FNXXU9CVB1 rebase: lineage-18.1-exynos7870-3.18-android-mainline-2.0

history: 7cd179c3f06 [FROMLIST-EXYNOS7870] [mm] mm: patch migrate.c
e37f1f9158e hugetlbfs: fix races and page leaks during migration
9b59612715f mm: migrate: don't rely on __PageMovable() of newpage after unlocking it
f46c09f2fa5 mm: migrate: hugetlb: putback destination hugepage to active list
8cf95002f0c Sanitize 'move_pages()' permission checks
5634b6de989 mm: Export migrate_page_move_mapping and migrate_page_copy
35d44e970eb mm/hugetlb: take page table lock in follow_huge_pmd()
d6d86c0a7f8 mm/balloon_compaction: redesign ballooned pages management
d3cb8bf6081 mm: migrate: Close race between migration completion and mprotect
0a31bc97c80 mm: memcontrol: rewrite uncharge API
8bdd6380916 mm: fix direct reclaim writeback regression
f72e7dcdd25 mm: let mm_find_pmd fix buggy race with THP fault
100873d7a77 hugetlb: rename hugepage_migration_support() to ..._supported()
68711a74634 mm, migration: add destination page freeing callback
11de9927f9d mm: numa: add migrated transhuge pages to LRU the same way as base pages
7e09e738afd mm: fix swapops.h:131 bug if remap_file_pages raced migration
e97ca8e5b86 mm: fix GFP_THISNODE callers and clarify
a3978a51946 mm/migrate.c: fix setting of cpupid on page migration twice against normal page
baae911b27b sched/numa: fix setting of cpupid on page migration twice
309381feaee mm: dump page when hitting a VM_BUG_ON using VM_BUG_ON_PAGE
78d5506e82b mm/migrate: remove unused function, fail_migrate_page()
59c82b70dcd mm/migrate: remove putback_lru_pages, fix comment on putback_movable_pages
32665f2bbfe mm/migrate: correct failure handling if !hugepage_migration_support()
354a3363363 mm/migrate: add comment about permanent failure path
af1839d722c mm: numa: trace tasks that fail migration due to rate limiting
1c5e9c27cbd mm: numa: limit scope of lock for NUMA migrate rate limiting
1c30e0177e4 mm: numa: make NUMA-migrate related functions static
051ac83adf6 mm/rmap: make rmap_walk to get the rmap_walk_control argument
8e321fefb0e aio/migratepages: make aio migrate pages sane
b0943d61b8f mm: numa: defer TLB flush for THP migration as long as possible
de466bd628e mm: numa: avoid unnecessary disruption of NUMA hinting during migration
eb4489f69f2 mm: numa: avoid unnecessary work on the failure path
f714f4f20e5 mm: numa: call MMU notifiers on THP migration
2b4847e7300 mm: numa: serialise parallel get_user_page against THP migration
30b0a105d9f mm: thp: give transparent hugepage code a separate copy_page
c4088ebdca6 mm: convert the rest to new page table lock api
cb900f41215 mm, hugetlb: convert hugetlbfs to use split pmd lock
fb10d5b7efb Merge branch 'linus' into sched/core
3f926ab945b mm: Close races between THP migration and PMD numa clearing
c3d16e16522 mm: migration: do not lose soft dirty bit if page is in migration state
7851a45cd3f mm: numa: Copy cpupid on page migration
90572890d20 mm: numa: Change page last {nid,pid} into {cpu,pid}
b795854b1fa sched/numa: Set preferred NUMA node based on number of private faults
1bc115d87df mm: numa: Scan pages with elevated page_mapcount
a54a407fbf7 mm: Close races between THP migration and PMD numa clearing
117aad1e9e4 mm: avoid reinserting isolated balloon pages into LRU lists
9bf12df31f2 Merge git://git.kvack.org/~bcrl/aio-next
6e543d5780e mm: vmscan: fix do_try_to_free_pages() livelock
83467efbdb7 mm: migrate: check movability of hugepage in unmap_and_move_huge_page()
e632a938d91 mm: migrate: add hugepage migration code to move_pages()
b8ec1cee5a4 mm: soft-offline: use migrate_pages() instead of migrate_huge_page()
31caf665e66 mm: migrate: make core migration code aware of hugepage
36bc08cc017 fs/aio: Add support to aio ring pages migration
30dad30922c mm: migration: add migrate_entry_wait_huge()
c2cc499c5bc mm compaction: fix of improper cache flush in migration code
c73e5c9c59a mm: rewrite the comment over migrate_pages() more comprehensibly
fed5b64a953 mm/migrate: fix comment typo syncronous->synchronous
9c620e2bc5a mm: remove offlining arg to migrate_pages
b79bc0a0c79 ksm: enable KSM page migration
c8d6553b958 ksm: make KSM page migration possible
22b751c3d03 mm: rename page struct field helpers
340ef3902cf mm: numa: cleanup flow of transhuge page migration
3abef4e6c23 mm: numa: take THP into account when migrating pages for NUMA balancing
be7517d6ab9 mm/hugetlb: set PTE as huge in hugetlb_change_protection and remove_migration_pte
04fa5d6a654 mm: migrate: check page_count of THP before migrating
ce4a9cc5793 mm,numa: fix update_mmu_cache_pmd call
3d59eebc5e1 Merge tag 'balancenuma-v11' of git://git.kernel.org/pub/scm/linux/kernel/git/mel/linux-balancenuma
389162c22dc mm,migrate: use N_MEMORY instead N_HIGH_MEMORY
5733c7d11df mm: introduce putback_movable_pages()
bf6bddf1924 mm: introduce compaction and migration for ballooned pages
78bd52097d0 mm: adjust address_space_operations.migratepage() return code
6219049ae1c mm: introduce mm_find_pmd()
4fc3f1d66b1 mm/rmap, migration: Make rmap_walk_anon() and try_to_unmap_anon() more scalable
d28d433512f mm: migrate: Account a transhuge page properly when rate limiting
7548341b289 mm: numa: Account for failed allocations and isolations as migration failures
220018d388b mm: numa: Add THP migration for the NUMA working set scanning fault case build fix
b32967ff101 mm: numa: Add THP migration for the NUMA working set scanning fault case.
bac0382c6ad mm: numa: migrate: Set last_nid on newly allocated page
e14808b49f5 mm: numa: Rate limit setting of pte_numa if node is saturated
a8f6077213d mm: numa: Rate limit the amount of memory that is migrated between nodes
03c5a6e1632 mm: numa: Add pte updates, hinting and migration stats
149c33e1c98 mm: migrate: Drop the misplaced pages reference count if the target node is full
7039e1dbec6 mm: migrate: Introduce migrate_misplaced_page()
7b2a2d4a18f mm: migrate: Add a tracepoint for migrate_pages
5647bc293ab mm: compaction: Move migration fail/success stats to migrate.c
0030f535a5c mm: memcg: fix compaction/migration failing due to memcg limits
8e6ac7fab37 hugetlb/cgroup: migrate hugetlb cgroup info from oldpage to new page during migration
189ebff2894 hugetlb: simplify migrate_huge_page()
752dc185dac mm: fix warning in __set_page_dirty_nobuffers
644473e9c60 Merge branch 'for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/ebiederm/user-namespace
b38a86eb196 userns: Convert the move_pages, and migrate_pages permission checks to use uid_eq
6e8b09eaf26 mm: fix NULL ptr dereference in move_pages
3268c63eded mm: fix move/migrate_pages() race on task struct
7512102cf64 memcg: fix GPF when cgroup removal races with last exit
35512ecaef0 mm: postpone migrated page mapping reset
a6bc32b8992 mm: compaction: introduce sync-light migration for use by compaction
b969c4ab9f1 mm: compaction: determine if dirty pages can be migrated without blocking within ->migratepage
4e5f01c2b9b memcg: clear pc->mem_cgroup if necessary.
faed836a237 mm/migrate.c: remove the unused macro lru_to_page
564c81db19f mm/migrate.c: cleanup comment for migration_entry_wait()
937a94c9db3 mm: migrate: one less atomic operation
09761333ed4 mm/migrate.c: pair unlock_page() and lock_page() when migrating huge pages
32aaeffbd4a Merge branch 'modsplit-Oct31_2011' of git://git.kernel.org/pub/scm/linux/kernel/git/paulg/linux
0dabec93de6 mm: migration: clean up unmap_and_move()
b95f1b31b75 mm: Map most files to use export.h instead of module.h
486cf46f3f9 mm: fix race between mremap and removing migration entry
99a15e21d96 migrate: don't account swapcache as shmem
746b18d421d mm: use refcounts for page_lock_anon_vma()
25985edcede Fix common misspellings
56039efa18f memcg: fix ugly initialization of return value is in caller
11bc82d67d1 mm: compaction: Use async migration for __GFP_NO_KSWAPD and enforce no writeback
9e60109f125 mm: rename drop_anon_vma() to put_anon_vma()
ef6a3c63112 mm: add replace_page_cache_page() function
a879bf582df mm: grab rcu read lock in move_pages()
48db54ee2f4 mm/migration: fix page corruption during hugepage migration
57fc4a5ee32 mm: when migrate_pages returns 0, all pages must have been released
28bd65781c8 mm: migration: clarify migrate_pages() comment
50de1dd967d memcg: fix memory migration of shmem swapcache
fd4a4663db2 mm: fix hugepage migration
1ce82b69e96 mm: fix migration hangs on anon_vma lock
29c1f677d42 mm: migration: use rcu_dereference_protected when dereferencing the radix tree slot during file page migration
500d65d4710 thp: pmd_trans_huge migrate bugcheck
7f0f24967b0 mm: migration: cleanup migrate_pages API by matching types for offlining and sync
77f1fe6b08b mm: migration: allow migration to operate asynchronously and avoid synchronous compaction in the faster path
3e7d3449706 mm: vmscan: reclaim order-0 and use compaction instead of lumpy reclaim
0d1836c3661 mm/migrate.c: fix compilation error
70384dc6dcc mm: fix error reporting in move_pages() syscall
cf608ac19c9 mm: compaction: fix COMPACTPAGEFAILED counting
1b430beee5e writeback: remove nonblocking/encountered_congestion references
3ef8fd7f720 Fix migration.c compilation on s390
290408d4a25 hugetlb: hugepage migration core
76545066c85 mm: extend KSM refcounts to the anon_vma root
012f18004da mm: always lock the root (oldest) anon_vma
cba48b98f23 mm: change direct call of spin_lock(anon_vma->lock) to inline function
ac39cf8cb86 memcg: fix mis-accounting of file mapped racy with migration
748446bb6b5 mm: compaction: memory compaction core
3fe2011ff51 mm: migration: allow the migration of PageSwapCache pages
67b9509b2c6 mm: migration: do not try to migrate unmapped anonymous pages
7f60c214fd3 mm: migration: share the anon_vma ref counts between KSM and page migration
3f6c82728f4 mm: migration: take a reference to the anon_vma before migrating
e13861d822f mm: remove return value of putback_lru_pages()
5a0e3ad6af8 include cleanup: Update gfp.h and slab.h includes to prepare for breaking implicit slab.h inclusion from percpu.h
85f1fb72fa7 mm/migrate.c: kill anon local variable from migrate_page_copy
ac0f6f927db Merge branch 'for-linus' of master.kernel.org:/home/rmk/linux-2.6-arm
87b8d1adefa mm: Make copy_from_user() in migrate.c statically predictable
4b3073e1c53 MM: Pass a PTE pointer to update_mmu_cache() rather than the PTE itself
6f5a55f1a6c Fix potential crash with sys_move_pages
418b27ef50e mm: remove unevictable_migrate_page function
62b61f611eb ksm: memory hotremove migration only
e9995ef978a ksm: rmap_walk to remove_migation_ptes
3ca7b3c5b64 mm: define PAGE_MAPPING_FLAGS
6d9c285a632 mm: move inc_zone_page_state(NR_ISOLATED) to just isolated place
b925585039c mm: Adjust do_pages_stat() so gcc can see copy_from_user() is safe
e00e431612c memcg: fix wrong pointer initialization at page migration when memcg is disabled.
db16826367f Merge branch 'hwpoison' of git://git.kernel.org/pub/scm/linux/kernel/git/ak/linux-mce-2.6
edcf4748cd5 mm: return boolean from page_has_private()
6c0b13519d1 mm: return boolean from page_is_file_cache()
a731286de62 mm: vmstat: add isolate pages
4b02108ac1b mm: oom analysis: add shmem vmstat
abfc3488118 memory hotplug: migrate swap cache page
14fa31b89c5 HWPOISON: Use bitmask/action code for try_to_unmap behaviour
35282a2de4e migration: only migrate_prep() once per move_pages()
6484eb3e2a8 page allocator: do not check NUMA node ID when the caller knows the node is valid
266cf658efc FS-Cache: Recruit a page flags for cache management
1001c9fb872 migration: migrate_vmas should check "vma"
938bb9f5e84 [CVE-2009-0029] System call wrappers part 28
01b1ae63c22 memcg: simple migration handling
7a81b88cb53 memcg: introduce charge-commit-cancel style of functions
6d91add09f4 mm: add Set,ClearPageSwapCache stubs
5bd1455c239 mm: move_pages: no need to set pp->page to ZERO_PAGE(0) by default
3140a227300 mm: rework do_pages_move() to work on page_sized chunks
cbacc2c7f06 Merge branch 'next' into for-linus
c095adbc211 mm: Don't touch uninitialized variable in do_pages_stat_array()
80bba1290ab mm: no get_user/put_user while holding mmap_sem in do_pages_stat?
ec98ce480ad Merge branch 'master' into next
bda8550deed migration: fix writepage error
2b828925652 Merge branch 'master' into next
c69e8d9c01d CRED: Use RCU to access another task's creds and to release a task's own creds
b6dff3ec5e1 CRED: Separate task security context from task_struct
76aac0e9a17 CRED: Wrap task credential accesses in the core kernel
0aedadf91a7 mm: move migrate_prep out from under mmap_sem
b7abea9630b memcg: make page->mapping NULL before uncharge
5e9a0f023be mm: extract do_pages_move() out of sys_move_pages()
2f007e74bb8 mm: don't vmalloc a huge page_to_node array for do_pages_stat()
e78bbfa8262 mm: stop returning -ENOENT from sys_move_pages() if nothing got migrated
b291f000393 mlock: mlocked pages are unevictable
894bc310419 Unevictable LRU Infrastructure
b2e185384f5 define page_file_cache() function
f04e9ebbe49 swap: use an array for the LRU pagevecs
62695a84eb8 vmscan: move isolate_lru_page() to vmscan.c
529ae9aaa08 mm: rename page trylock
19fd6231279 mm: spinlock tree_lock
e286781d5f2 mm: speculative page references
69029cd5502 memcg: remove refcnt from page_cgroup
e8589cc189f memcg: better migration handling
83d1674a946 mm: make CONFIG_MIGRATION available w/o CONFIG_NUMA
4f5ca265788 mm/migrate.c should #include <linux/syscalls.h>
cde53535991 Christoph has moved
89f5b7da2a6 Reinstate ZERO_PAGE optimization in 'get_user_pages()' and fix XIP
3a902c5f685 mm: fix warning on memory offline
98837c7f82e memcg: fix VM_BUG_ON from page migration
ae41be37429 bugfix for memory cgroup controller: migration under memory controller fix
e1a1cd590e3 Memory controller: make charging gfp mask aware
8a9f3ccd247 Memory controller: memory accounting
62e1c55300f page migraton: handle orphaned pages
698dd4ba6b1 maps4: move is_swap_pte
e9534b3fd78 Typo fixes retrun -> return
228ebcbe634 Uninline find_task_by_xxx set of functions
b488893a390 pid namespaces: changes to show virtual ids to user
954ffcb35f5 flush icache before set_pte() on ia64: flush icache at set_pte
97ee0524614 flush cache before installing new page at migraton
56bbd65df0e Memoryless nodes: Update memory policy and page migration
9d966d495c4 mm/migrate.c __user annotation
989f89c57e6 fix rcu_read_lock() in page migraton
3dd9fe8c397 memory unplug: isolate_lru_page fix
dc386d4d1e9 memory unplug: migration by kernel
769848c0389 Add __GFP_MOVABLE for callers to flag allocations from high memory that may be migrated
0e8c7d0fd5b page migration: fix NR_FILE_PAGES accounting
0dc952dc3e6 [PATCH] Page migration: Fix vma flag checking
7cf9c2c76c1 [PATCH] radix-tree: RCU lockless readside
8ce08464d2c [PATCH] Fix sys_move_pages when a NULL node list is passed
9361401eb76 [PATCH] BLOCK: Make it possible to disable the block layer [try #6]
b398f6bff93 [PATCH] BLOCK: Stop fallback_migrate_page() from using page_has_buffers() [try #6]
980128f223f [PATCH] Define easier to handle GFP_THISNODE
3d99cfb5f46 [PATCH] sys_move_pages: Do not fall back to other nodes
e6a1530d692 [PATCH] Allow migration of mlocked pages
7b2259b3e53 [PATCH] page migration: Support a vma migration function
86c3a7645c0 [PATCH] SELinux: add security_task_movememory calls to mm code
742755a1d8c [PATCH] page migration: sys_move_pages(): support moving of individual pages
95a402c3847 [PATCH] page migration: use allocator function for migrate_pages()
aaa994b300a [PATCH] page migration: handle freeing of pages in migrate_pages()
e24f0b8f76c [PATCH] page migration: simplify migrate_pages()
04e62a29bf1 [PATCH] More page migration: use migration entries for file pages
442c9137de8 [PATCH] More page migration: do not inc/dec rss counters
6c5240ae7f4 [PATCH] Swapless page migration: modify core logic
d75a0fcda2c [PATCH] Swapless page migration: rip out swap based logic
0697212a411 [PATCH] Swapless page migration: add R/W migration entries
8351a6e4785 [PATCH] page migration cleanup: move fallback handling into special function
2d1db3b1170 [PATCH] page migration cleanup: pass "mapping" to migration functions
c3fcf8a5daa [PATCH] page migration cleanup: extract try_to_unmap from migration functions
5b5c7120e21 [PATCH] page migration cleanup: drop nr_refs in remove_references()
e7340f73307 [PATCH] page migration cleanup: remove useless definitions
1d8b85ccf1e [PATCH] page migration cleanup: group functions
4c28f81193b [PATCH] page migration: Fix fallback behavior for dirty pages
64a3ca5f7ec [PATCH] mm/migrate.c: don't export a static function
e23ca00bf1b [PATCH] Some page migration fixups
b20a35035f9 [PATCH] page migration reorg