[FROMLIST-EXYNOS7870] [ipc] ipc: patch shm.c
original base: A600FNXXU9CVB1 rebase: lineage-18.1-exynos7870-3.18-android-mainline-2.0

history: 392f9854b33 [FROMLIST-EXYNOS7870] [ipc] ipc: patch shm.c
1a7de43a021 Initialize msg/shm IPC objects before doing ipc_addid()
bf77b94c99a ipc/shm: kill the historical/wrong mm->start_stack check
83293c0f5a6 shm: allow exit_shm in parallel if only marking orphans
ab602f79915 shm: make exit_shm work proportional to task activity
1376327ce1f ipc/shm.c: check for integer overflow during shmget.
09c6eb1f651 ipc/shm.c: check for overflows of shm_tot
247a8ce8229 ipc/shm.c: check for ulong overflows in shmat
46c0a8ca3e8 ipc, kernel: clear whitespace
7153e402731 ipc, kernel: use Linux headers
eb66ec44f86 ipc: constify ipc_ops
8001c85810d ipc: standardize code comments
239521f31d7 ipc: whitespace cleanup
0f3d2b0135f ipc: introduce ipc_valid_object() helper to sort out IPC_RMID races
3a72660b07d ipc,shm: correct error return value in shmctl (SHM_UNLOCK)
a399b29dfba ipc,shm: fix shm_file deletion races
53dad6d3a8e ipc: fix race with LSMs
7a25dd9e042 ipc, shm: drop shm_lock_check
530fcd16d87 ipc, shm: guard against non-existant vma in shmdt(2)
d9a605e40b1 ipc: rename ids->rw_mutex
c2c737a0461 ipc,shm: shorten critical region for shmat
f42569b1388 ipc,shm: cleanup do_shmat pasta
2caacaa82a5 ipc,shm: shorten critical region for shmctl
c97cb9ccab8 ipc,shm: make shmctl_nolock lockless
68eccc1dc34 ipc,shm: introduce shmctl_nolock
79ccf0f8c8e ipc,shm: shorten critical region in shmctl_down
8b8d52ac382 ipc,shm: introduce lockless functions to obtain the ipc object
7b4cc5d8411 ipc: move locking out of ipcctl_pre_down_nolock
cf9d5d78d05 ipc: close open coded spin lock calls
dbfcd91f06f ipc: move rcu lock out of ipc_addid
c103a4dc4a3 ipc/shmc.c: eliminate ugly 80-col tricks
091d0d55b28 shm: fix null pointer deref when userspace specifies invalid hugepage size
af73e4d9506 hugetlbfs: fix mmap failure in unaligned size request
d69f3bad467 ipc: sysv shared memory limited to 8TiB
d895cb1af15 Merge branch 'for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/viro/vfs
41badc15cba mm: make do_mmap_pgoff return populate as a size in bytes, not as a bool
bebeb3d68b2 mm: introduce mm_populate() for populating new vmas
39b65252745 fs: Preserve error code in get_empty_filp(), part 2
496ad9aa8ef new helper: file_inode(file)
42d7395feb5 mm: support more pagesizes for MAP_HUGETLB/SHM_HUGETLB
1efdb69b0bb userns: Convert ipc to use kuid and kgid where appropriate
079a96ae387 ipc: add COMPAT_SHMLBA support
7d8a45695cc ipc: shm: restore MADV_REMOVE functionality on shared memory segments
e3fc629d7bb switch aio and shm to do_mmap_pgoff(), make do_mmap() static
8b3ec6814c8 take security_mmap_file() outside of ->mmap_sem
40716e29243 hugetlbfs: fix alignment of huge page requests
245132643e1 SHM_UNLOCK: fix Unevictable pages stranded after swap
85046579bde SHM_UNLOCK: fix long unpreemptible section
140d0b2108f Do 'shm_init_ns()' in an early pure_initcall
298507d4d2c shm: optimize exit_shm()
33a30ed4bdc shm: fix wrong tests
4c677e2eefd shm: optimize locking and ipc_namespace getting
5774ed014f0 shm: handle separate PID namespaces case
b34a6b1da37 ipc: introduce shm_rmid_forced sysctl
02c24a82187 fs: push i_mutex and filemap_write_and_wait down into ->fsync() handlers
ca16d140af9 mm: don't access vm_flags as 'int'
25985edcede Fix common misspellings
b0e77598f87 userns: user namespaces: convert several capable() calls
3af54c9bd9e ipc: shm: fix information leak to userland
b795218075a ipc/shm.c: add RSS and swap size information to /proc/sysvipc/shm
6038f373a3d llseek: automatically add .llseek fop
7ea8085910e drop unused dentry argument to ->fsync
f1eb1332b8f ipc: use rlimit helpers
ed5e5894b23 nommu: fix SYSV SHM for NOMMU
bac5e54c29f Merge branch 'master' of git://git.kernel.org/pub/scm/linux/kernel/git/viro/vfs-2.6
0552f879d45 Untangling ima mess, part 1: alloc_file()
2c48b9c4557 switch alloc_file() to passing struct path
7d6feeb287c ipc ns: fix memory leak (idr)
c4caa778157 file ->get_unmapped_area() shouldn't duplicate work of get_unmapped_area()
f0f37e2f777 const: mark struct vm_struct_operations
6bfde05bf5c hugetlbfs: allow the creation of files suitable for MAP_PRIVATE on the vfs internal mount
2195d2818c3 fix undefined reference to user_shm_unlock
353d5c30c66 mm: fix hugetlb bug due to user_shm_unlock call
73fbad283cf Merge branch 'next' into for-linus
586c7e6a280 shm: fix unused warnings on nommu
c9d9ac525a0 integrity: move ima_counts_get
b9fc745db83 integrity: path_check update
e562aebc6cc ipc: make shm_get_stat() more robust
703a3cd7281 Merge branch 'master' into next
5a6fe125950 Do not account for the address space used by hugetlbfs using VM_ACCOUNT
cb5629b10d6 Merge branch 'master' into next
1df9f0a7317 Integrity: IMA file free imbalance
a68e61e8ff2 shm: fix shmctl(SHM_INFO) lockup with !CONFIG_SHMEM
fc8744adc87 Stop playing silly games with the VM_ACCOUNT flag
d5460c9974a [CVE-2009-0029] System call wrappers part 25
8feae13110d NOMMU: Make VMAs per MM as for MMU-mode linux
e8148f75880 ipc: clean up ipc/shm.c
a33e6751003 sanitize audit_ipc_obj()
86a264abe54 CRED: Wrap current->cred and a few other accessors
b6dff3ec5e1 CRED: Separate task security context from task_struct
414c0708d0d CRED: Wrap task credential accesses in the SYSV IPC subsystem
aeb5d727062 [PATCH] introduce fmode_t, do annotations
89e004ea55a SHM_LOCKED pages are unevictable
00c2bf85d8f ipc: get rid of ipc_lock_down()
a5516438959 hugetlb: modular state for hugetlb page size
6c826818ff5 /proc/sysvipc/shm: fix 32-bit truncation of segment sizes
c592713b3e1 shm: Remove silly double assignment
a5f75e7f256 IPC: consolidate all xxxctl_down() functions
8f4a3809c18 IPC: introduce ipc_update_perm()
016d7132f24 IPC: get rid of the use *_setbuf structure.
8d4cc8b5c5e IPC/shared memory: introduce shmctl_down
48dea404ed0 IPC: use ipc_buildid() directly from ipc_addid()
52cd3b07405 mempolicy: rework mempolicy Reference Counting [yet again]
ae4d8c16aa2 mempolicy: fixup Fallback for Default Shmem Policy
69682d852f5 mempolicy: fix reference counting bugs
01b8b07a5d7 IPC: consolidate sem_exit_ns(), msg_exit_ns() and shm_exit_ns()
ed2ddbf88c0 IPC: make struct ipc_ids static in ipc_namespace
ae5e1b22f17 namespaces: move the IPC namespace under IPC_NS option
b1ed88b47f5 IPC: fix error check in all new xxx_lock() and xxx_exit_ns() functions
283bb7fada7 IPC: fix error case when idr-cache is empty in ipcget()
1b531f21366 ipc: remove unneeded parameters
3e148c79938 fix idr_find() locking
f4566f04854 ipc: fix wrong comments
03f02c7657f Storing ipcs into IDRs
023a53557ea ipc: integrate ipc_checkid() into ipc_lock()
637c3663402 ipc: remove the ipc_get() routine
7748dbfaa01 ipc: unify the syscalls code
7ca7e564e04 ipc: store ipcs into IDRs
b488893a390 pid namespaces: changes to show virtual ids to user
ce8d2cdf3d2 r/o bind mounts: filesystem helpers for custom 'struct file's
d823e3e7541 ipc/shm.c: make 2 functions static
7be77e20d59 Fix user struct leakage with locked IPC shem segment
2e92a3baee6 NOMMU: Fix SYSV IPC SHM
d0217ac04ca mm: fault feedback #1
54cb8821de0 mm: merge populate and nopage into fault (fixes nonlinear)
7d69a1f4a72 remove CONFIG_UTS_NS and CONFIG_IPC_NS
9d66586f772 shm: fix the filename of hugetlb sysv shared memory
22741925d26 hugetlb: fix get_policy for stacked shared memory files
30475cc12a5 Restore shmid as inode# to fix /proc/pid/maps ABI breakage
516dffdcd88 [PATCH] Fix get_unmapped_area and fsync for hugetlb shm segments
de01bad2f5d [PATCH] make ipc/shm.c:shm_nopage() static
bc56bba8f31 [PATCH] shm: make sysv ipc shared memory use stacked files
9a32144e9d7 [PATCH] mark struct file_operations const 7
f66d45e99eb [PATCH] correct sys_shmget allocation check
6d63079adde [PATCH] struct path: convert ipc
c7e12b83898 [PATCH] Fix ipc entries removal
4e9823111bd [PATCH] IPC namespace - shm
6ab3d5624e1 Remove obsolete #include <linux/config.h>
185606fc6a1 [PATCH] remove unused o_flags from do_shmat
ac03221a4fd [PATCH] update of IPC audit record cleanup
073115d6b29 [PATCH] Rework of IPC auditing
b78b6af66a5 [PATCH] shmat: stop mprotect from giving write permission to a readonly attachment (CVE-2006-1524)
9ba025f1088 BUG_ON() Conversion in ipc/shm.c
5f921ae96f1 [PATCH] sem2mutex: ipc, id.sem
1b9a3917366 Merge branch 'audit.b3' of git://git.kernel.org/pub/scm/linux/kernel/git/viro/audit-current
df1e2fb5403 [PATCH] shmdt: check address alignment
8c8570fb8fe [PATCH] Capture selinux subject/object context information.
8e36709d8ce [PATCH] shmdt cannot detach not-alined shm segment cleanly.
c59ede7b78d [PATCH] move capable() to capability.h
b33291c0bce [PATCH] ipc: expand shm_flags
b0e15190ead [PATCH] NOMMU: Make SYSV IPC SHM use ramfs facilities on NOMMU
bf8f972d3a1 [PATCH] SHM_NORESERVE flags for shmget()
551110a94aa [PATCH] hugetlb: remove repeated code
19b4946ca9d [PATCH] ipc: convert /proc/sysvipc/* to generic seq_file interface
6ade43fbbcc [PATCH] shm: CONFIG_SHMEM=n build fix
7d87e14c236 [PATCH] consolidate sys_shmat
1da177e4c3f Linux-2.6.12-rc2