[FROMLIST-EXYNOS7870] [drivers] cpuidle: governors: patch menu.c
original base: A600FNXXU9CVB1 rebase: lineage-18.1-exynos7870-3.18-android-mainline-2.0

history: 73e27c9c538 [FROMLIST-EXYNOS7870] [drivers] cpuidle: governors: patch menu.c
00e6d24c7dc cpuidle: governor: menu: don't use loadavg
229b6863b2c drivers/cpuidle: Replace __get_cpu_var uses for address calculation
c9d26423e56 Merge tag 'pm+acpi-3.17-rc1-2' of git://git.kernel.org/pub/scm/linux/kernel/git/rafael/linux-pm
158c12948f3 Merge branch 'for-linus' of git://git.kernel.org/pub/scm/linux/kernel/git/jikos/trivial
372ba8cb46b cpuidle: menu: Lookup CPU runqueues less
64b4ca5cb6e cpuidle: menu: Call nr_iowait_cpu less times
107d4f4601a cpuidle: menu: Use ktime_to_us instead of reinventing the wheel
ae779300603 cpuidle: menu: Use shifts when calculating averages where possible
8804ed155a5 cpuidle: menu governor - remove unused macro STDDEV_THRESH
2fba5376ed7 cpuidle: fix comment
bed4d597a0f cpuidle / menu: move repeated correction factor check to init
3836785a1bd cpuidle / menu: Return (-1) if there are no suitable states
96e95182e95 cpuidle: Move perf multiplier calculation out of the selection loop
61c66d6efa2 cpuidle: Do not substract exit latency from assumed sleep length
7ac26436677 cpuidle: Ensure menu coefficients stay within domain
22695ab6314 cpuidle: Use actual state latency in menu governor
5dc2f5a3030 cpuidle: rename expected_us to next_timer_us in menu governor
51f245b895e cpuidle: Change struct menu_device field types
decd51bbcd7 cpuidle: Add a comment warning about possible overflow
0e96d5adcfe cpuidle: Fix variable domains in get_typical_interval()
939e33b7fcd cpuidle: Fix menu_device->intervals type
4cd46bca8ca cpuidle: CodingStyle: Break up multiple assignments on single line
0d6a7ffa4cc cpuidle: Check called function parameter in get_typical_interval()
017099e25fb cpuidle: Rearrange code and comments in get_typical_interval()
330647a9501 cpuidle: Ignore interval prediction result when timer is shorter
ee42f75dba3 Merge back earlier 'pm-cpuidle' material.
148519120c6 Revert "cpuidle: Quickly notice prediction failure for repeat mode"
228b30234f2 Revert "cpuidle: Quickly notice prediction failure in general case"
137b944e100 cpuidle: Make it clear that governors cannot be modules
8aef33a7cf4 cpuidle: remove the power_specified field in the driver
0e5537b30d3 cpuidle: Fix finding state with min power_usage
a093b93ee0e cpuidle: fix a suspicious RCU usage in menu governor
c96ca4fb76b cpuidle: Get typical recent sleep interval
e11538d1f03 cpuidle: Quickly notice prediction failure in general case
69a37beabf1 cpuidle: Quickly notice prediction failure for repeat mode
cbc9ef0287a PM / Domains: Add preliminary support for cpuidle, v2
dc7fd275ae6 cpuidle: move field disable from per-driver to per-cpu
02401c06b7f cpuidle: power_usage should be declared signed integer
3a53396b038 cpuidle: add a sysfs entry to disable specific C state for debug purpose.
3c00303206c Merge branch 'release' of git://git.kernel.org/pub/scm/linux/kernel/git/lenb/linux
46bcfad7a81 cpuidle: Single/Global registration of idle states
b25edc42bfb cpuidle: Remove CPUIDLE_FLAG_IGNORE and dev->prepare()
e978aa7d7d5 cpuidle: Move dev->last_residency update to driver enter routine; remove dev->last_state
884b17e109d cpuidle: Add module.h to drivers/cpuidle files as required.
e8db0be1245 PM QoS: Move and rename the implementation files
7467571f448 cpuidle: menu: fixed wrapping timers at 4.294 seconds
20e3341bb13 cpuidle: Fix typos
71abbbf856a cpuidle: extend cpuidle and menu governor to handle dynamic states
8c215bd3890 sched: Cure nr_iowait_cpu() users
1f85f87d4f8 cpuidle: add a repeating pattern detector to the menu governor
ed77134bfcc PM QOS update
1c6fe0364fa cpuidle: Fix incorrect optimization
56e6943b414 cpuidle menu: remove 8 bytes of padding on 64 bit builds
5787536edf1 drivers/cpuidle/governors/menu.c: fix undefined reference to `__udivdi3'
672917dcc78 cpuidle: menu governor: reduce latency on exit
69d25870f20 cpuidle: fix the menu governor to boost IO performance
816bb611e41 cpuidle: Add decaying history logic to menu idle predictor
320eee77635 cpuidle: Menu governor fix wrong usage of measured_us
a2bd9202335 cpuidle: Do not use poll_idle unless user asks for it
d82b35186ea pm qos infrastructure and interface
4f86d3a8e29 cpuidle: consolidate 2.6.22 cpuidle branch into one patch