[FROMLIST-EXYNOS7870] [net] netfilter: patch Kconfig
original base: A600FNXXU9CVB1 rebase: lineage-18.1-exynos7870-3.18-android-mainline-2.0

history: d997b16d385 [FROMLIST-EXYNOS7870] [net] netfilter: patch Kconfig
66861a10c08 netfilter: xt_quota2: make quota2_log work well
e47d455f06a BACKPORT: netfilter: Kconfig: get rid of parens around depends on
917596c2800 netfilter: fixup the quota2, and enable.
8468092ab61 netfilter: add xt_qtaguid matching module
739e4a758e0 Merge git://git.kernel.org/pub/scm/linux/kernel/git/davem/net
e7af85db544 Merge git://git.kernel.org/pub/scm/linux/kernel/git/pablo/nf
0aac3833536 Merge git://git.kernel.org/pub/scm/linux/kernel/git/pablo/nf-next
9ba1f726bec netfilter: nf_tables: add new nft_masq expression
679ab4ddbdf netfilter: xt_TPROXY: undefined reference to `udp6_lib_lookup'
84a59ca55f6 netfilter: add explicit Kconfig for NETFILTER_XT_NAT
d79a61d646d netfilter: NETFILTER_XT_TARGET_LOG selects NF_LOG_*
1e8430f30b5 netfilter: nf_tables: nat expression must select CONFIG_NF_NAT
c1878869c0c netfilter: fix several Kconfig problems in NF_LOG_*
83e96d443b3 netfilter: log: split family specific code to nf_log_{ip,ip6,common}.c files
05513e9e33d netfilter: nf_tables: add reject module for NFPROTO_INET
cc4723ca316 netfilter: nft_reject: split up reject module into IPv4 and IPv6 specifc parts
5ff1dd24168 Merge branch 'master' of git://git.kernel.org/pub/scm/linux/kernel/git/pablo/nftables
419331d8ff0 netfilter: Add dependency on IPV6 for NF_TABLES_INET
ef8570d859a Merge branch 'master' of git://git.kernel.org/pub/scm/linux/kernel/git/pablo/nf-next
74f77a6b2b1 netfilter: introduce l2tp match extension
1d49144c0aa netfilter: nf_tables: add "inet" table for IPv4/IPv6
9aa28f2b710 Merge branch 'master' of git://git.kernel.org/pub/scm/linux/kernel/git/pablo/nftables
82a37132f30 netfilter: x_tables: lightweight process control group matching
d497c635273 netfilter: add help information to new nf_tables Kconfig options
bee11dc78fc netfilter: nft_reject: support for IPv6 and TCP reset
5f291c2869a netfilter: select NFNETLINK when enabling NF_TABLES
6a649f33980 netfilter: add IPv4/6 IPComp extension match support
0aff078d58e netfilter: nft: add queue module
4819224853d netfilter: fix connlimit Kconfig prompt string
eb31628e37a netfilter: nf_tables: Add support for IPv6 NAT
0ca743a5599 netfilter: nf_tables: add compatibility layer for x_tables
20a69341f2d netfilter: nf_tables: add netlink set API
96518518cc4 netfilter: add nftables
1a5bbfc3d6b netfilter: Fix build errors with xt_socket.c
48b1de4c110 netfilter: add SYNPROXY core/target
fd158d79d33 netfilter: tproxy: remove nf_tproxy_core, keep tw sk assigned to skb
06991c28f37 Merge tag 'driver-core-3.9-rc1' of git://git.kernel.org/pub/scm/linux/kernel/git/gregkh/driver-core
35612a229c3 netfilter: fix missing dependencies for NETFILTER_XT_MATCH_CONNLABEL
e6f30c73171 netfilter: x_tables: add xt_bpf match
c539f01717c netfilter: add connlabel conntrack extension
663ef0d1842 net/netfilter: remove depends on CONFIG_EXPERIMENTAL
757ae316fb3 netfilter: fix missing dependencies for the NOTRACK target
10db9069eb5 netfilter: xt_CT: recover NOTRACK target support
2cbc78a29e7 netfilter: combine ipt_REDIRECT and ip6t_REDIRECT
b3d54b3e406 netfilter: combine ipt_NETMAP and ip6t_NETMAP
965505015be netfilter: remove xt_NOTRACK
320ff567f29 netfilter: nf_nat: support IPv6 in TFTP NAT helper
5901b6be885 netfilter: nf_nat: support IPv6 in IRC NAT helper
9a664821068 netfilter: nf_nat: support IPv6 in SIP NAT helper
ee6eb966737 netfilter: nf_nat: support IPv6 in amanda NAT helper
d33cbeeb1a4 netfilter: nf_nat: support IPv6 in FTP NAT helper
c7232c9979c netfilter: add protocol independent NAT core
7c622345472 netfilter: nfnetlink_queue: fix compilation with NF_CONNTRACK disabled
6e9c2db3aa8 netfilter: fix compilation of the nfnl_cthelper if NF_CONNTRACK is unset
12f7a505331 netfilter: add user-space connection tracking helper infrastructure
cf308a1fae4 netfilter: add xt_hmark target for hash-based skb marking
dd705072412 netfilter: nf_ct_ext: add timeout extension
50978462300 netfilter: add cttimeout infrastructure for fine timeout tuning
6939c33a757 netfilter: merge ipt_LOG and ip6_LOG into xt_LOG
bc94b521675 netfilter: Kconfig: fix unmet xt_nfacct dependencies
54b07dca685 netfilter: provide config option to disable ancient procfs parts
d446a8202c8 netfilter: xtables: move ipt_ecn to xt_ecn
ceb98d03eac netfilter: xtables: add nfacct match to support extended accounting
9413902796f netfilter: add extended accounting infrastructure over nfnetlink
3ced1be5490 netfilter: Remove ADVANCED dependency from NF_CONNTRACK_NETBIOS_NS
46a246c4dff netfilter: Remove NOTRACK/RAW dependency on NETFILTER_ADVANCED.
395cf9691d7 doc: fix broken references
b7225041e93 netfilter: xt_addrtype: replace rt6_lookup with nf_afinfo->route
2f5dc631239 netfilter: xt_addrtype: ipv6 support
de81bbea176 netfilter: ipt_addrtype: rename to xt_addrtype
9291747f118 netfilter: xtables: add device group match
d956798d82d netfilter: xtables: "set" match and "SET" target support
a7b4f989a62 netfilter: ipset: IP set core support
a992ca2a049 netfilter: nf_conntrack_tstamp: add flow-based timestamp extension
93557f53e1f netfilter: nf_conntrack: nf_conntrack snmp helper
5f2cafe7367 netfilter: Kconfig: NFQUEUE is useless without NETFILTER_NETLINK_QUEUE
43f393caec0 netfilter: audit target to record accepted/dropped packets
c7066f70d96 netfilter: fix Kconfig dependencies
f6318e55880 netfilter: fix module dependency issues with IPv6 defragmentation, ip6tables and xt_TPROXY
e8648a1fdb5 netfilter: add xt_cpu match
9c3e1c39679 netfilter: xt_ipvs (netfilter matcher for IPVS)
edf0e1fb0d0 netfilter: add CHECKSUM target
d70a011dbba netfilter: complete the deprecation of CONFIG_NF_CT_ACCT
fe6fb552858 netfilter: fix simple typo in KConfig for netfiltert xt_TEE
0902b469bd2 netfilter: xtables: idletimer target implementation
83827f6a891 netfilter: xt_TEE depends on NF_CONNTRACK
9b7ce2b7626 netfilter: xtables: add missing depends for xt_TEE
e281b19897d netfilter: xtables: inclusion of xt_TEE
115bc8f2874 netfilter: xtables: resort osf kconfig text
5be4a4f5898 netfilter: xt_recent: remove old proc directory
b8f00ba27e4 netfilter: xtables: merge xt_CONNMARK into xt_connmark
28b949885f8 netfilter: xtables: merge xt_MARK into xt_mark
44c5873199a netfilter: xtables: add comment markers to Xtables Kconfig
5d0aa2ccd46 netfilter: nf_conntrack: add support for "conntrack zones"
84f3bb9ae9d netfilter: xtables: add CT target
9cbc1cb8cd4 Merge branch 'master' of master.kernel.org:/pub/scm/linux/kernel/git/torvalds/linux-2.6
4737f0978d6 trivial: Kconfig: .ko is normally not included in module names
11eeef41d5f netfilter: passive OS fingerprint xtables match
acda0743902 xt_socket: checks for the state of nf_conntrack
4b070662493 netfilter: Kconfig: TProxy doesn't depend on NF_CONNTRACK
3ae16f13027 netfilter: fix selection of "LED" target in netfilter
692105b8ac5 trivial: fix typos/grammar errors in Kconfig texts
a9a9adfe2f9 netfilter: fix xt_LED build failure
0269ea49373 netfilter: xtables: add cluster match
268cb38e180 netfilter: x_tables: add LED trigger target
cfac5ef7b92 netfilter: Combine ipt_ttl and ip6t_hl source
563d36eb3fb netfilter: Combine ipt_TTL and ip6t_HL source
293a4f28333 netfilter: xt_NFLOG is dependant of nfnetlink_log
041fb574c75 netfilter: ctnetlink: remove obsolete NAT dependency from Kconfig
db2bf2476b2 Merge branch 'lvs-next-2.6' of git://git.kernel.org/pub/scm/linux/kernel/git/horms/lvs-2.6
f39a9410ed0 netfilter: xtables: remove bogus mangle table dependency of connmark
c2df73de246 netfilter: xtables: use "if" blocks in Kconfig
aba0d34800d netfilter: xtables: sort extensions alphabetically in Kconfig
e84392707e1 netfilter: iptables TPROXY target
136cdc71fd5 netfilter: iptables socket match
9ad2d745a23 netfilter: iptables tproxy core
079aa88fe71 netfilter: xt_recent: IPv6 support
e948b20a71a netfilter: rename ipt_recent to xt_recent
cb7f6a7b716 IPVS: Move IPVS to net/netfilter/ipvs
584015727a3 netfilter: accounting rework: ct_extend + 64bit counters (v4)
b11c16beb92 netfilter: Get rid of refrences to no longer existant Fast NAT.
f3261aff35c netfilter: Kconfig: default DCCP/SCTP conntrack support to the protocol config values
2bc780499aa [NETFILTER]: nf_conntrack: add DCCP protocol support
f72e25a897c [NETFILTER]: Rename ipt_iprange to xt_iprange
8ce22fcab43 [NETFILTER]: Remove some EXPERIMENTAL dependencies
b26e76b7ce3 [NETFILTER]: Hide a few more options under NETFILTER_ADVANCED
33b8e776056 [NETFILTER]: Add CONFIG_NETFILTER_ADVANCED option
2eeeba390ae [NETFILTER]: Select CONFIG_NETFILTER_NETLINK when needed
ab4f58c77a1 [NETFILTER]: remove NF_CONNTRACK_ENABLED option
50c164a81f1 [NETFILTER]: x_tables: add rateest match
5859034d7eb [NETFILTER]: x_tables: add RATEEST target
5c350e5a380 [NETFILTER]: IPv6 capable xt_TOS v1 target
c9fd4968095 [NETFILTER]: Merge ipt_TOS into xt_DSCP
c3b33e6a2cd [NETFILTER]: Merge ipt_tos into xt_dscp
4c37799ccf6 [NETFILTER]: Use lowercase names for matches in Kconfig
0265ab44bac [NETFILTER]: merge ipt_owner/ip6t_owner in xt_owner
338e8a79262 [NETFILTER]: x_tables: add TCPOPTSTRIP target
e403149c92a Kbuild/doc: fix links to Documentation files
ee4411a1b1e [NETFILTER]: x_tables: add xt_time match
3fd8f9e4b6c [NETFILTER]: xt_connlimit needs to depend on nf_conntrack
59eecdfb166 [NETFILTER]: nf_conntrack: UDPLITE support
370786f9cfd [NETFILTER]: x_tables: add connlimit match
ba9dda3ab5a [NETFILTER]: x_tables: add TRACE target
1b50b8a371e [NETFILTER]: Add u32 match
3dde6ad8fc3 Fix trivial typos in Kconfig* files
39f5fb30351 kconfig: fix path to modules.txt in Kconfig help
587aa64163b [NETFILTER]: Remove IPv4 only connection tracking/NAT
ca8fbb859c4 [NETFILTER]: nf_conntrack_netlink: add missing dependency on NF_NAT
a3c941b08d7 [NETFILTER]: Kconfig: improve dependency handling
cdd289a2f83 [NETFILTER]: add IPv6-capable TCPMSS target
6fecd198511 [NETFILTER]: Add SANE connection tracking helper
3e8219806c3 [NETFILTER]: nf_conntrack_h323: fix compile error with CONFIG_IPV6=m, CONFIG_NF_CONNTRACK_H323=y
2e553023664 [NETFILTER]: xt_hashlimit: fix ip6tables dependency
c9386cfddc1 [NETFILTER]: New connection tracking is not EXPERIMENTAL anymore
3a411355bcf [NETFILTER]: Fix INET=n linking error
a3c479772c9 [NETFILTER]: Mark old IPv4-only connection tracking scheduled for removal
a536df35b3a [NETFILTER]: nf_conntrack/nf_nat: add TFTP helper port
9fafcd7b203 [NETFILTER]: nf_conntrack/nf_nat: add SIP helper port
f09943fefe6 [NETFILTER]: nf_conntrack/nf_nat: add PPTP helper port
92703eee4cc [NETFILTER]: nf_conntrack: add NetBIOS name service helper port
869f37d8e48 [NETFILTER]: nf_conntrack/nf_nat: add IRC helper port
f587de0e2fe [NETFILTER]: nf_conntrack/nf_nat: add H.323 helper port
16958900578 [NETFILTER]: nf_conntrack/nf_nat: add amanda helper port
b321e14425c [NETFILTER]: Kconfig: improve conntrack selection
baf7b1e1128 [NETFILTER]: x_tables: add NFLOG target
39b46fc6f0d [NETFILTER]: x_tables: add port of hashlimit match for IPv4 and IPv6
c08de5d5308 [NETFILTER]: xt_CONNSECMARK: fix Kconfig dependencies
f1da70632fa [NETFILTER]: Kconfig: fix xt_physdev dependencies
a468701db58 [NETFILTER]: x_tables: replace IPv4 DSCP target by address family independent version
9ba1627617d [NETFILTER]: x_tables: replace IPv4 dscp match by address family independent version
d5af981e93a [NETFILTER]: Demote xt_sctp to EXPERIMENTAL
68c1692e3ea [NETFILTER]: statistic match: add missing Kconfig help text
100468e9c05 [SECMARK]: Add CONNSECMARK xtables target
7c9728c393d [SECMARK]: Add secmark support to conntrack
5e6874cdb8d [SECMARK]: Add xtables SECMARK target
f3389805e53 [NETFILTER]: x_tables: add statistic match
62b7743483b [NETFILTER]: x_tables: add quota match
a89ecb6a2ef [NETFILTER]: x_tables: unify IPv4/IPv6 multiport match
dc5ab2faece [NETFILTER]: x_tables: unify IPv4/IPv6 esp match
50b521aa54f [NETFILTER]: Fix Kconfig typos
c4b88513920 [NETFILTER]: x_tables: replace IPv4/IPv6 policy match by address family independant version
deac0ccdb4d [NETFILTER]: x_tables: fix dependencies of conntrack related modules
a6c1cd57264 [NETFILTER] Fix Kconfig menu level for x_tables
2e4e6a17af3 [NETFILTER] x_tables: Abstraction layer for {ip,ip6,arp}_tables
c1d10adb4a5 [NETFILTER]: Add ctnetlink port for nf_conntrack
a7957563330 [NETFILTER]: Mark ctnetlink as EXPERIMENTAL
9fb9cbb1082 [NETFILTER]: Add nf_conntrack subsystem.
0597f2680d6 [NETFILTER]: Add new "nfnetlink_log" userspace packet logging facility
7af4cc3fa15 [NETFILTER]: Add "nfnetlink_queue" netfilter queue handler over nfnetlink
f9e815b376d [NETFITLER]: Add nfnetlink layer.